# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- master
- poc/*

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: dotnet tool install fake-cli --tool-path .
  # Run Build with Test target when not merging a release branch into master
  #- script: .\build.cmd Test
  #condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) 

  # Run Build which will by default run the unit tests
  - script: .\build.cmd Test.NetStandard

  #- task: CopyFiles@2
  #  inputs:
  #    contents: build_output\*.nupkg
  #    targetFolder: $(Build.ArtifactStagingDirectory)
  #    flattenFolders: true
  #- task: PublishBuildArtifacts@1
  #  inputs:
  #    pathtoPublish: $(Build.ArtifactStagingDirectory)
  #    artifactName: Windows
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: '**/build/test/**/*.xml'
      testRunTitle: '$(Agent.JobName)'

variables:
  solution: 'src/IO.Ably.NetFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'